version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.2
    - 3.6.3
  - dependency-name: "@angular/language-service"
    versions:
    - 11.0.5
    - 11.1.1
  - dependency-name: core-js
    versions:
    - 3.8.1
    - 3.8.3
  - dependency-name: typescript
    versions:
    - 4.0.5
  - dependency-name: tslib
    versions:
    - 2.0.3
